/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

import java.util.Collections;
import java.util.LinkedList;
import java.util.Iterator;
import java.util.Queue;
import java.util.ArrayList;

import p1s1.GUISubscribedObserver;

/**
 *
 * @author jesus
 */
public class GUIInterface extends javax.swing.JDialog {
    
    GUISubscribedObserver observer;
    
    Queue<Double> cola;
    ArrayList<Integer> tiempo_historico;
    int tiempo_actual;
    static final int GRAPHIC_SIZE = 3;

    /**
     * Creates new form GUIInterface
     */
    public GUIInterface(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cola = new LinkedList<Double>();
        tiempo_historico = new ArrayList<Integer>();
        tiempo_actual = 0;
        
        setVisible(true);
    }
    
    public void setObserver(GUISubscribedObserver observer){
        this.observer = observer;
        NombreClase.setText(observer.getClass().getSimpleName());
        
        repaint();
        revalidate();
    }
    
    public void generarGrafica(int periodo){
        DefaultCategoryDataset datos = new DefaultCategoryDataset();
        JFreeChart barra = null;
        
        double valor = observer.getValor();
        cola.add(valor);
        
        tiempo_actual += periodo/1000;
        tiempo_historico.add(tiempo_actual);
        
        int contador = 0;
        
        if(cola.size() > GRAPHIC_SIZE){
            cola.remove();
            tiempo_historico.remove(0);
        }
        
        for(Double item: cola){
            
            double auxValor = item;
            int auxTiempo = tiempo_historico.get(contador);

            contador++;

            datos.setValue(auxValor,String.valueOf(auxTiempo),"");
        }

        barra = ChartFactory.createBarChart3D("ValorCripto","Tiempo(s)","Valor",datos,PlotOrientation.VERTICAL,true,true,false);
        
        BufferedImage graficoBarra = barra.createBufferedImage(500, 500);
        
        Grafica.setSize(PanelGrafica.getSize());
        Grafica.setIcon(new ImageIcon(graficoBarra));
        
        PanelGrafica.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextoClase = new javax.swing.JLabel();
        PanelGrafica = new javax.swing.JPanel();
        Grafica = new javax.swing.JLabel();
        NombreClase = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TextoClase.setText("Tipo de Observador:");
        TextoClase.setEnabled(false);

        javax.swing.GroupLayout PanelGraficaLayout = new javax.swing.GroupLayout(PanelGrafica);
        PanelGrafica.setLayout(PanelGraficaLayout);
        PanelGraficaLayout.setHorizontalGroup(
            PanelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGraficaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Grafica)
                .addContainerGap(190, Short.MAX_VALUE))
        );
        PanelGraficaLayout.setVerticalGroup(
            PanelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGraficaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Grafica)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        NombreClase.setText("jTextField1");
        NombreClase.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextoClase)
                .addGap(44, 44, 44)
                .addComponent(NombreClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoClase)
                    .addComponent(NombreClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(269, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUIInterface dialog = new GUIInterface(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Grafica;
    private javax.swing.JTextField NombreClase;
    private javax.swing.JPanel PanelGrafica;
    private javax.swing.JLabel TextoClase;
    // End of variables declaration//GEN-END:variables
}