/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

import java.util.Collections;
import java.util.LinkedList;
import java.util.Iterator;
import java.util.Queue;
import java.util.ArrayList;

import p1s1.GUIVIPSubscribedObserver;

/**
 *
 * @author jesus
 */
public class GUIVIPInterface extends javax.swing.JDialog {

    GUIVIPSubscribedObserver observer;
    
    Queue<Double> cola;
    ArrayList<Integer> tiempo_historico;
    int tiempo_actual;
    static final int GRAPHIC_SIZE = 3;
    
    /**
     * Creates new form GUIVIPInterface
     */
    public GUIVIPInterface(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cola = new LinkedList<Double>();
        tiempo_historico = new ArrayList<Integer>();
        tiempo_actual = 0;
        
        setVisible(true);
    }
    
    public void setObserver(GUIVIPSubscribedObserver observer){
        this.observer = observer;
        NombreClase.setText(observer.getClass().getSimpleName());
        
        repaint();
        revalidate();
    }
    
    public void setValorObservable(double valor){
        observer.setValorObservable(valor);
    }
    
    public void generarGrafica(int periodo){
        DefaultCategoryDataset datos = new DefaultCategoryDataset();
        JFreeChart barra = null;
        
        double valor = observer.getValor();
        cola.add(valor);
        
        tiempo_actual += periodo/1000;
        tiempo_historico.add(tiempo_actual);
        
        int contador = 0;
        
        if(cola.size() > GRAPHIC_SIZE){
            cola.remove();
            tiempo_historico.remove(0);
        }
        
        for(Double item: cola){
            
            double auxValor = item;
            int auxTiempo = tiempo_historico.get(contador);

            contador++;

            datos.setValue(auxValor,String.valueOf(auxTiempo),"");
        }

        barra = ChartFactory.createBarChart3D("ValorCripto","Tiempo(s)","Valor",datos,PlotOrientation.VERTICAL,true,true,false);
        
        BufferedImage graficoBarra = barra.createBufferedImage(500, 500);
        
        Grafica.setSize(PanelGrafica.getSize());
        Grafica.setIcon(new ImageIcon(graficoBarra));
        
        PanelGrafica.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextoClase = new javax.swing.JLabel();
        NombreClase = new javax.swing.JTextField();
        PanelGrafica = new javax.swing.JPanel();
        Grafica = new javax.swing.JLabel();
        WriteArea = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TextoClase.setText("Tipo de Observador:");
        TextoClase.setEnabled(false);

        NombreClase.setText("jTextField1");
        NombreClase.setEnabled(false);

        javax.swing.GroupLayout PanelGraficaLayout = new javax.swing.GroupLayout(PanelGrafica);
        PanelGrafica.setLayout(PanelGraficaLayout);
        PanelGraficaLayout.setHorizontalGroup(
            PanelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGraficaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Grafica)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        PanelGraficaLayout.setVerticalGroup(
            PanelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGraficaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Grafica)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        WriteArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WriteAreaActionPerformed(evt);
            }
        });

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(WriteArea, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(TextoClase)
                            .addGap(74, 74, 74)
                            .addComponent(NombreClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(62, 62, 62)
                            .addComponent(PanelGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(Submit)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Submit)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextoClase)
                            .addComponent(NombreClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PanelGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WriteArea, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WriteAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WriteAreaActionPerformed

    }//GEN-LAST:event_WriteAreaActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        double valor;
        String texto = WriteArea.getText();
        try{
            valor = Double.parseDouble(texto);
            setValorObservable(valor);
        } catch (NumberFormatException e) {
            System.err.println("No es un formato válido");
        }
    }//GEN-LAST:event_SubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIVIPInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIVIPInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIVIPInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIVIPInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUIVIPInterface dialog = new GUIVIPInterface(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Grafica;
    private javax.swing.JTextField NombreClase;
    private javax.swing.JPanel PanelGrafica;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel TextoClase;
    private javax.swing.JTextField WriteArea;
    // End of variables declaration//GEN-END:variables
}
